global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "agents"
    static_configs:
      - targets:
          - "host.docker.internal:8001"
          - "host.docker.internal:8002"
          - "host.docker.internal:8003"
          - "host.docker.internal:8004"
          - "host.docker.internal:8005"
          - "host.docker.internal:8006"
